# FUNCTION TO CONVERT LINKED LIST INTO AN ARRAY FOR EASIER SORTING
# THIS HELPER FUNCTION TRAVERSES A LINKED LIST AND BUILDS A STANDARD PYTHON LIST
# THIS IS USEFUL BECAUSE MANY SORTING ALGORITHMS ARE EASIER TO APPLY TO ARRAYS
def converter(linkedList):
    """
    CONVERTS LINKED LIST INTO AN ARRAY FOR COMPARATIVELY EASY SORTING
    PARAMS:
        linkedList - LINKED LIST OF EVENT OBJECTS
    RETURNS:
        res - ARRAY BUILT FROM LINKED LIST ELEMENTS
    """
    # INITIALIZE EMPTY PYTHON LIST THAT WILL STORE EVENTS FROM LINKED LIST
    res = []
    # START TRAVERSAL AT THE HEAD NODE OF linkedlist
    curr = linkedList.head
    # ITERATE THROUGH THE LINKED LIST NODE BY NODE UNTIL REACHING THE END (None)
    # EACH NODE STORES AN Event OBJECT IN curr.event
    while curr:
        res.append(curr.event)
        curr = curr.next
    # RETURN COMPLETED ARRAY CONTAINING ALL EVENTS FROM LINKED LIST
    return res
