# FUNCTION FOR CREATION OF RANDOM EVENTS
"""
WHY THIS EXISTS:
    WE NEED TO TEST AT n = 50, 500, 5000, 50000 TO SEE MEANINGFUL CURVES
    THIS GENERATOR PRODUCES RANDOM, UNSORTED EVENTS SO OUR SORTING BENCHMARKS 
    REFLECT REAL WORLD "MESSY" INPUT CONDITIONS, NOT BEST CASE SCENARIOS
    
"""

# IMPORT random MODULE FOR GENERATING RANDOM NUMBERS
import random
# IMPORT Event CLASS SO GENERATED EVENTS CAN BE CREATED
from event_creator import Event

# LIST OF POSSIBLE EVENT TITLES USED BY THE RANDOM GENERATOR
# RANDOM SELECTION FROM THIS LIST MAKES EVENTS MORE REALISTIC
titles = [
    "Club Meeting", "Guest Lecture", "Hackathon", "Concert", "Exam Review",
    "Career Fair", "Art Show", "Movie Night", "Study Hall", "Workshop",
    "Orientation", "Panel Discussion", "Fitness Class", "Game Night", "Seminar",
    "Research Symposium", "Open Mic", "Networking Event", "Fundraiser", "Sports Game"
]

# LIST OF POSSIBLE EVENT LOCATIONS USED BY THE RANDOM GENERATOR
# THESE REPRESENT COMMON LOCATIONS AROUND CAMPUS
locations = [
    "UMC", "C4C", "Norlin Library", "CASE", "ATLAS", "Rec Center",
    "Macky Auditorium", "Fleming Law", "Muenzinger", "Duane Physics",
    "Ekeley", "Ketchum Arts", "Wolf Law", "Engineering Center", "Folsom Field"
]

# FUNCTION TO CREATE A SINGLE RANDOM EVENT OBJECT
def createEvent():
    """
    CREATES A SINGLE RANDOM EVENT.
    DATE FORMAT:  YYYY-MM-DD  
    TIME FORMAT:  HH:MM       
    RANDOM DATE:
        - YEAR ALWAYS 2026 
        - MONTH IS 1-12
        - DAY IS 1-28 TO AVOID FEB 30, APRIL 31, ETC.
    RANDOM TIME:
        - HOUR: 0-23 (24 HOUR CLOCK) 
                REALISTICALLY, MOST EVENTS WILL FALL BETWEEN 0800-1800
                BUT THERE MIGHT BE SOME OVERNIGHT CLEANING OR STARGAZING EVENT
                THAT COULD RUN AFTER HOURS, SO WE KEEP THE FULL 0-23 
        - MINUTE: 00, 15, 30, or 45
    """
    # FIXED YEAR FOR DATASET CONSISTENCY
    year  = 2026
    # RANDOM MONTH BETWEEN JAN AND DEC
    month = random.randint(1, 12)
    # RANDOM DAY BETWEEN 1 AND 28 TO AVOID INVALID CALENDAR DATES
    day   = random.randint(1, 28)
    # RANDOM HOUR IN 24-HOUR CLOCK FORMAT
    hour  = random.randint(0, 23)
    # RANDOM MINUTE SELECTED FROM COMMON 15 MIN SCHEDULING INTERVALS
    minute = random.choice([0, 15, 30, 45])

    # zfill(2) PADS OUR SINGLE DIGIT TIMES WITH A LEADING ZERO: 3 = "03", 11 = "11"
    # ENSURES FORMAT ALWAYS YYYY-MM-DD and HH:MM, SINCE SORT COMPARES DATES AS STRINGS
    # ONLY WORKS CORRECTLY IF FORMAT IS ZERO-PADDED
    date = f"{year}-{str(month).zfill(2)}-{str(day).zfill(2)}"
    time = f"{str(hour).zfill(2)}:{str(minute).zfill(2)}"

    # RANDOMLY SELECT EVENT TITLE FROM titles LIST
    title    = random.choice(titles)
    # RANDOMLY SELECT EVENT LOCATION FROM locations LIST
    location = random.choice(locations)

    # CREATE AND RETURN A NEW Event OBJECT
    # id IS AUTOMATICALLY GENERATED BY event_creator.unique_ID()
    return Event(title, date, time, location)


# FUNCTION TO GENERATE MULTIPLE RANDOM EVENTS
def genEvents(n):
    """
    CREATES lIST OF n RANDOM, UNSORTED EVENT OBJECTS
    PARAMS:
        n - NUMBER OF EVENTS TO GENERATE
    RETURNS:
        events - LIST OF n EVENT OBJECTS
        
    """
    # INITIALIZE EMPTY LIST TO STORE GENERATED EVENTS
    events = []
    # LOOP n TIMES TO CREATE n RANDOM EVENTS
    for i in range(n):    
        # CALL createEvent() AND APPEND RESULTING Event OBJECT TO events LIST
        events.append(createEvent())
    # RETURN LIST OF GENERATED EVENTS
    return events




# QUICK SMOKE TEST: THIS BLOCK ONLY EXECUTES WHEN FILE IS RUN DIRECTLY
# IT DOES NOT EXECUTE IF THIS FILE IS IMPORTED BY ANOTHER MODULE
# THIS IS A COMMON PYTHON TESTING PATTERN
if __name__ == "__main__":
    # GENERATE A SMALL SAMPLE OF EVENTS FOR TESTING
    sample = genEvents(5)
    # PRINT HEADER TO IDENTIFY SAMPLE OUTPUT
    print("Sample of 5 randomly generated events:")
    # PRINT EACH EVENT USING Event.__repr__()
    for e in sample:
        print(" ", e)
